[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PRIVATE_KEY,FIREBASE_CLIENT_EMAIL,FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_APP_ID,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,PAYFAST_PASSPHRASE,PAYFAST_MERCHANT_KEY,PAYFAST_MERCHANT_ID,PAYFAST_ENV,NEXTAUTH_SECRET,OPENROUTER_API_KEY,GOOGLE_CLIENT_SECRET"

[[plugins]]
  package = "@netlify/plugin-nextjs"
