// src/server/services/screening.service.ts
/**
 * Driver Screening Service (V1 — deterministic rules)
 * =============================================================================
 * What this file does
 * -------------------
 * Produces a driver screening result in the contract-defined shape:
 * - score (0–100)
 * - decision (accept/reject/review)
 * - reasonCodes (machine-readable justification)
 * - riskFlags / missingFields (structured signals)
 * - explanation (human-readable; generated by provider "none" in V1)
 *
 * Why this exists
 * ---------------
 * Business-facing flows require consistent, auditable screening outputs.
 * This service centralises screening logic so API routes/components do not
 * duplicate policy logic or produce inconsistent decisions.
 *
 * POPIA (South Africa) considerations
 * ----------------------------------
 * - Data minimisation: the input should be the minimum operational fields
 *   needed for screening. No raw document images/files should be passed in.
 * - Purpose specification: evaluation is strictly for operational screening.
 * - Safeguards: output avoids personal identifiers and sensitive details.
 *
 * IMPORTANT RULE
 * --------------
 * Decisions are produced by deterministic rules in this service.
 * Providers may only generate the `explanation` field and must not alter:
 * - score
 * - decision
 * - reasonCodes
 */

import {
  clampScore0to100,
  type DriverScreeningResult,
  type MissingField,
  type ReasonCode,
  type RiskFlag,
} from "../ai/contract";
import { buildMeta, getAIProvider } from "../ai";

/**
 * Policy version for screening rules.
 *
 * Guidance:
 * - Bump whenever weights/thresholds/disqualifiers change.
 * - Keep versioning explicit for audit trails and regression tests.
 */
const SCREENING_POLICY_VERSION = "screening_rules_v1.0.0";

/**
 * Minimal input model for V1 screening.
 *
 * Design notes:
 * - This type is intentionally lightweight and non-invasive to existing DB shapes.
 * - This is NOT a final “domain model”; it is a service input contract.
 * - Optional fields allow gradual adoption while the product stabilises.
 *
 * Data minimisation note:
 * - Avoid passing names, phone numbers, emails, or raw text blobs.
 * - Use booleans/status flags rather than raw documents.
 */
export interface DriverScreeningInput {
  driverId: string;

  /** Profile completeness signals (no PII). */
  hasProfileBasics?: boolean; // e.g., essential profile fields present
  hasLocation?: boolean;
  hasAvailability?: boolean;

  /** Compliance/document signals. */
  documentsStatus?: "verified" | "pending" | "missing" | "rejected";

  /** Training signals (V1 uses boolean; can be expanded to module arrays later). */
  trainingStatus?: "complete" | "incomplete" | "missing";

  /** Experience/rating signals (optional). */
  yearsExperience?: number; // number of years (if known)
  ratingAverage?: number; // 0..5 (if known)

  /**
   * Disqualifier flags (examples).
   * These should be derived from internal checks, not user-supplied text.
   */
  disqualifiers?: {
    /** True indicates the application must be rejected per policy. */
    policyDisqualifier?: boolean;
    /** True indicates suspicious pattern requiring manual review. */
    fraudSignal?: boolean;
    /** True indicates safety concern requiring manual review. */
    safetyConcern?: boolean;
  };
}

/**
 * Computes missing fields from the provided input.
 *
 * Why it exists:
 * - Missing fields drive the "review" decision.
 * - UI can map these labels to action items (“upload docs”, “complete training”).
 */
function computeMissingFields(input: DriverScreeningInput): MissingField[] {
  const missing: MissingField[] = [];

  // Profile basics: a coarse signal for “core profile fields exist”.
  if (!input.hasProfileBasics) missing.push("other"); // mapped to “complete profile basics”
  if (!input.hasLocation) missing.push("location");
  if (!input.hasAvailability) missing.push("availability");

  // Documents/training: explicit missing categories.
  if (!input.documentsStatus || input.documentsStatus === "missing") missing.push("documents");
  if (!input.trainingStatus || input.trainingStatus === "missing") missing.push("training");

  return missing;
}

/**
 * Computes risk flags from the input.
 *
 * Risk flags are intended to:
 * - trigger manual review
 * - increase conservatism in decisions
 *
 * Note:
 * - Risk flags should stay operational and non-sensitive.
 */
function computeRiskFlags(input: DriverScreeningInput): RiskFlag[] {
  const flags: RiskFlag[] = [];

  if (input.disqualifiers?.fraudSignal) flags.push("FRAUD_SIGNAL");
  if (input.disqualifiers?.safetyConcern) flags.push("SAFETY_CONCERN");

  // Example: documents rejected implies potential mismatch or invalid submission.
  if (input.documentsStatus === "rejected") flags.push("DOCUMENT_SUSPICIOUS");

  return flags.length ? flags : [];
}

/**
 * Computes reason codes based on inputs and intermediate signals.
 *
 * Reason codes are used for:
 * - explainability
 * - UI messaging
 * - analytics
 * - regression tests
 */
function computeReasonCodes(params: {
  input: DriverScreeningInput;
  missingFields: MissingField[];
  riskFlags: RiskFlag[];
  score: number;
}): ReasonCode[] {
  const codes: ReasonCode[] = [];

  // Missing/quality signals.
  if (params.missingFields.length > 0) {
    codes.push("MISSING_REQUIRED_FIELDS");
    if (params.missingFields.includes("documents")) codes.push("MISSING_DOCUMENTS");
    if (params.missingFields.includes("training")) codes.push("MISSING_TRAINING");
    codes.push("INCOMPLETE_PROFILE");
  }

  // Risk signals.
  if (params.riskFlags.length > 0) codes.push("HIGH_RISK_FLAG");
  if (params.input.disqualifiers?.policyDisqualifier) codes.push("POLICY_DISQUALIFIER");

  // Fit/strength signals (minimal V1 heuristics).
  if (typeof params.input.yearsExperience === "number") {
    if (params.input.yearsExperience >= 2) codes.push("STRONG_EXPERIENCE_MATCH");
    else codes.push("WEAK_EXPERIENCE_MATCH");
  }

  if (typeof params.input.ratingAverage === "number") {
    if (params.input.ratingAverage >= 4.5) codes.push("RATING_HIGH");
    else if (params.input.ratingAverage < 3.5) codes.push("RATING_LOW");
  }

  if (params.input.hasAvailability) codes.push("AVAILABILITY_MATCH");
  else codes.push("AVAILABILITY_MISMATCH");

  // Default code to ensure at least one reason exists for downstream display logic.
  if (codes.length === 0) codes.push("RULES_ENGINE_DEFAULT");

  return codes;
}

/**
 * Computes a deterministic score (0–100).
 *
 * V1 scoring is intentionally simple and transparent.
 * It can be refined once owners provide:
 * - definitive weights
 * - thresholds
 * - disqualifier rules
 *
 * Scoring strategy (V1 baseline):
 * - Start at 0
 * - Add points for completeness/verification
 * - Subtract for missing fields and rejected documents
 * - Clamp to 0..100
 */
function computeScore(input: DriverScreeningInput, missingFields: MissingField[], riskFlags: RiskFlag[]): number {
  let score = 0;

  // Positive signals.
  if (input.hasProfileBasics) score += 15;
  if (input.hasLocation) score += 10;
  if (input.hasAvailability) score += 10;

  if (input.documentsStatus === "verified") score += 25;
  if (input.documentsStatus === "pending") score += 10;

  if (input.trainingStatus === "complete") score += 20;
  if (input.trainingStatus === "incomplete") score += 10;

  // Optional performance signals.
  if (typeof input.yearsExperience === "number") {
    score += input.yearsExperience >= 2 ? 10 : 5;
  }
  if (typeof input.ratingAverage === "number") {
    // Rating is out of 5; map roughly into 0..10.
    score += Math.max(0, Math.min(10, Math.round(input.ratingAverage * 2)));
  }

  // Negative signals.
  if (missingFields.length > 0) score -= missingFields.length * 8;
  if (input.documentsStatus === "rejected") score -= 20;

  // Risk flags reduce score slightly but primarily influence decision.
  if (riskFlags.length > 0) score -= riskFlags.length * 5;

  // Hard disqualifier should strongly reduce score (decision is handled separately).
  if (input.disqualifiers?.policyDisqualifier) score -= 50;

  return clampScore0to100(score);
}

/**
 * Computes a deterministic decision from score + disqualifiers + missing/risk signals.
 *
 * Decision strategy (V1 baseline):
 * - policy disqualifier → reject
 * - missing required fields/documents/training → review
 * - risk flags present → review
 * - score threshold → accept/reject
 *
 * NOTE:
 * - Thresholds are placeholders until owners confirm business rules.
 */
function computeDecision(params: {
  input: DriverScreeningInput;
  score: number;
  missingFields: MissingField[];
  riskFlags: RiskFlag[];
}): DriverScreeningResult["decision"] {
  // Hard policy disqualifier overrides everything.
  if (params.input.disqualifiers?.policyDisqualifier) return "reject";

  // Missing critical info prevents full evaluation.
  if (params.missingFields.length > 0) return "review";

  // Risk flags require human review even if score is high.
  if (params.riskFlags.length > 0) return "review";

  // Baseline thresholds (to be confirmed by owners).
  if (params.score >= 70) return "accept";
  if (params.score < 50) return "reject";
  return "review";
}

/**
 * Public API: evaluates a driver application and returns a contract-compliant result.
 *
 * Implementation outline:
 * 1) compute missing fields and risk flags
 * 2) compute score and decision deterministically
 * 3) generate reason codes
 * 4) generate explanation via provider (V1 = none templates)
 * 5) return full DriverScreeningResult with audit metadata
 */
export async function evaluateDriverScreening(params: {
  input: DriverScreeningInput;
  traceId?: string;
}): Promise<DriverScreeningResult> {
  const { input, traceId } = params;

  // Step 1: compute structured signals for completeness and risk.
  const missingFields = computeMissingFields(input);
  const riskFlags = computeRiskFlags(input);

  // Step 2: compute deterministic score and decision.
  const score = computeScore(input, missingFields, riskFlags);
  const decision = computeDecision({ input, score, missingFields, riskFlags });

  // Step 3: compute reason codes for explainability and analytics.
  const reasonCodes = computeReasonCodes({ input, missingFields, riskFlags, score });

  // Step 4: confidence reflects completeness (lower when missing/risk implies review).
  // This is not a “model confidence”; it is an operational confidence signal.
  const confidence =
    missingFields.length > 0 || riskFlags.length > 0 || decision === "review" ? 0.7 : 1.0;

  // Step 5: provider explanation is derived from structured signals only.
  const provider = getAIProvider();
  const explanation = await provider.explain({
    feature: "driver_screening",
    reasonCodes,
    score,
    decision,
    missingFields,
    riskFlags,
  });

  // Step 6: attach audit metadata.
  const meta = buildMeta({
    provider: provider.name,
    policyVersion: SCREENING_POLICY_VERSION,
    traceId,
    // model intentionally omitted in V1 (no external provider).
  });

  // Final: return contract-compliant result.
  return {
    feature: "driver_screening",
    meta,
    confidence,
    score,
    decision,
    reasonCodes,
    riskFlags: riskFlags.length ? riskFlags : undefined,
    missingFields: missingFields.length ? missingFields : undefined,
    explanation,
  };
}
