// src/server/ai/contract.ts
/**
 * AI / Rules Contract (V1)
 * =============================================================================
 * What this file does
 * -------------------
 * Defines the stable, versioned TypeScript contract used by:
 * - Driver application screening (score + decision + reasons)
 * - Job-to-driver matching (ranked recommendations + reasons)
 * - Business insights (text answer + optional metrics)
 *
 * This contract is designed to remain stable even if an external AI provider
 * is introduced later. The decision logic is expected to remain deterministic
 * and auditable.
 *
 * Design principles
 * -----------------
 * 1) Vendor optionality:
 *    - V1 works without any external AI vendor.
 *    - Future providers may enhance explanations only.
 *
 * 2) Auditability:
 *    - Every output includes `meta` with contract version and policy version.
 *    - Outputs include `reasonCodes` for machine-readable justification.
 *
 * 3) Privacy & POPIA (South Africa):
 *    - This file defines outputs that should be safe to store and display.
 *    - Metadata must not include PII.
 *    - Reason codes and flags should represent operational signals, not
 *      personal identifiers or sensitive attributes.
 *
 * IMPORTANT RULE
 * --------------
 * Any future “AI provider” must not modify score/decision/reason codes.
 * Providers may only create or enhance the `explanation` field.
 */

/** Contract schema version for downstream compatibility checks. */
export const AI_CONTRACT_VERSION = "v1" as const;

/**
 * Provider identifiers.
 * V1 uses "none" to indicate vendor-free, deterministic operation.
 */
export type AIProviderName = "none" | "google" | "openai" | "other";

/**
 * Decision outcomes for screening-like flows.
 * - accept: meets minimum requirements per policy
 * - reject: fails policy requirements (hard fail or low score)
 * - review: requires human review (missing data or risk flags)
 */
export type Decision = "accept" | "reject" | "review";

/**
 * Reason codes are machine-readable and stable.
 *
 * Why reason codes exist:
 * - Provide explainability without revealing sensitive details.
 * - Enable consistent UI messaging and analytics.
 * - Allow regression testing when policy logic changes.
 *
 * How to extend:
 * - Add new codes rather than changing meanings of existing ones.
 * - Keep names operational (not personal/sensitive).
 */
export type ReasonCode =
  // Data quality / missing inputs
  | "MISSING_REQUIRED_FIELDS"
  | "MISSING_DOCUMENTS"
  | "MISSING_TRAINING"
  | "INCOMPLETE_PROFILE"
  // Risk / compliance
  | "HIGH_RISK_FLAG"
  | "POLICY_DISQUALIFIER"
  | "LOW_TRUST_SIGNAL"
  // Fit / scoring
  | "STRONG_EXPERIENCE_MATCH"
  | "WEAK_EXPERIENCE_MATCH"
  | "AVAILABILITY_MATCH"
  | "AVAILABILITY_MISMATCH"
  | "DISTANCE_OK"
  | "DISTANCE_FAR"
  | "RATING_HIGH"
  | "RATING_LOW"
  // General / fallback
  | "RULES_ENGINE_DEFAULT";

/**
 * Risk flags represent higher severity issues requiring attention.
 *
 * Guidance:
 * - Keep flags generic and operational.
 * - Avoid flags that encode sensitive personal characteristics.
 * - Use flags to trigger manual review rather than automated outcomes.
 */
export type RiskFlag =
  | "DOCUMENT_SUSPICIOUS"
  | "IDENTITY_UNVERIFIED"
  | "BACKGROUND_CHECK_PENDING"
  | "PRIOR_COMPLAINTS"
  | "SAFETY_CONCERN"
  | "FRAUD_SIGNAL"
  | "OTHER";

/**
 * Missing field labels communicate what is required to complete evaluation.
 *
 * Guidance:
 * - Prefer generic labels rather than raw form field names.
 * - Keep the set limited and stable so UI can map labels to instructions.
 */
export type MissingField =
  | "fullName"
  | "phone"
  | "email"
  | "license"
  | "vehicle"
  | "availability"
  | "location"
  | "training"
  | "documents"
  | "experience"
  | "rating"
  | "other";

/**
 * Explanation is display-friendly and safe for business users.
 *
 * The explanation content is expected to be:
 * - concise
 * - actionable
 * - non-sensitive
 *
 * In V1, explanations are generated by templates (none provider).
 * In future, a provider may enhance wording, but not decisions.
 */
export interface Explanation {
  /** Short summary (typically 1–2 sentences). */
  summary: string;

  /** Optional bullet list of strengths. */
  strengths?: string[];

  /** Optional bullet list of concerns/gaps. */
  concerns?: string[];

  /** Optional next action guidance for operations. */
  recommendedNextAction?: string;
}

/**
 * Metadata required for auditability and debugging.
 *
 * Safety constraints:
 * - Must be PII-free.
 * - Must not contain raw application text.
 * - Must not contain document identifiers or attachment URLs.
 */
export interface ContractMeta {
  /** Contract schema version to support backwards compatibility. */
  contractVersion: typeof AI_CONTRACT_VERSION;

  /** Provider name used for explanation generation (or "none"). */
  provider: AIProviderName;

  /**
   * Policy version identifies the rules/scoring revision used.
   * Example: "screening_rules_v1.0.0"
   *
   * This should change whenever thresholds/weights/disqualifiers change.
   */
  policyVersion: string;

  /** UTC timestamp for when this output was generated. */
  generatedAt: string;

  /** Optional correlation ID for tracing logs across systems. */
  traceId?: string;

  /** Optional model identifier (only applicable if external provider is used). */
  model?: string;
}

/**
 * Base output shared by all AI/rules feature results.
 *
 * This base guarantees:
 * - metadata for audit trails
 * - confidence for UI behavior (optional gating)
 * - structured justification via reason codes and flags
 */
export interface ContractOutputBase {
  /** Audit/debug metadata for the result. */
  meta: ContractMeta;

  /**
   * Confidence in the result (0..1).
   *
   * Intended usage:
   * - 1.0 when evaluation has complete information and deterministic rules.
   * - Lower values when missing fields reduce certainty or require review.
   */
  confidence: number;

  /** Machine-readable justification for the output. */
  reasonCodes: ReasonCode[];

  /** High-severity signals requiring manual review (optional). */
  riskFlags?: RiskFlag[];

  /** Missing information preventing a full evaluation (optional). */
  missingFields?: MissingField[];

  /** Human-readable explanation safe for UI display (optional). */
  explanation?: Explanation;
}

/**
 * Driver screening output contract.
 *
 * What this represents:
 * - An evaluation of a driver application against business policy.
 */
export interface DriverScreeningResult extends ContractOutputBase {
  feature: "driver_screening";

  /** 0–100 score produced by rules/policy. */
  score: number;

  /** Policy decision derived from score + disqualifiers + risk thresholds. */
  decision: Decision;
}

/**
 * A single candidate recommendation returned by job matching.
 *
 * Design note:
 * - `driverId` should be an internal reference ID.
 * - No PII (name/phone/email) should be returned by default in this object.
 */
export interface MatchCandidate {
  driverId: string;
  score: number; // 0–100
  reasonCodes: ReasonCode[];
  riskFlags?: RiskFlag[];
  explanation?: Explanation;
}

/**
 * Job matching output contract.
 *
 * What this represents:
 * - Ranked recommendations for a job based on driver/job constraints.
 */
export interface JobMatchingResult extends ContractOutputBase {
  feature: "job_matching";

  /** Sorted best → worst candidates. */
  candidates: MatchCandidate[];

  /** Optional note when there are no viable candidates. */
  note?: string;
}

/**
 * Business insights output contract (V1 template-driven).
 *
 * What this represents:
 * - A concise operational answer to a known category of business questions.
 * - Optional metrics that support the answer.
 */
export interface BusinessInsightsResult extends ContractOutputBase {
  feature: "business_insights";

  /** Human-readable answer (safe for business UI display). */
  answer: string;

  /** Optional structured metrics supporting the answer. */
  metrics?: Record<string, number | string | boolean | null>;
}

/** Union type for any feature output. */
export type AIContractOutput =
  | DriverScreeningResult
  | JobMatchingResult
  | BusinessInsightsResult;

/**
 * Utility: returns an ISO timestamp in UTC.
 *
 * Why it exists:
 * - Ensures consistent timestamps in audit metadata regardless of server locale.
 */
export function nowUtcIso(): string {
  return new Date().toISOString();
}

/**
 * Utility: clamps a numeric score to 0..100 and rounds it.
 *
 * Why it exists:
 * - Prevents invalid scores from leaking to the UI or storage.
 * - Ensures consistent integer scoring semantics across services.
 */
export function clampScore0to100(score: number): number {
  if (Number.isNaN(score)) return 0;
  return Math.max(0, Math.min(100, Math.round(score)));
}
